name-template: '🚀 Release - $NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'

commitish: main
filter-by-commit-message: true

categories:
  - title: '✨ Features'
    commit-message-regex: '^feat(\(.+\))?:'
  - title: '🐛 Fixes'
    commit-message-regex: '^fix(\(.+\))?:'
  - title: '📚 Documentation'
    commit-message-regex: '^docs(\(.+\))?:'
  - title: '🔨 Refactoring'
    commit-message-regex: '^refactor(\(.+\))?:'
  - title: '✅ Tests'
    commit-message-regex: '^test(\(.+\))?:'
  - title: '🧹 Chores'
    commit-message-regex: '^chore(\(.+\))?:'
  - title: '📦 Miscellaneous'
    commit-message-regex: '.*'

change-template: '- $EMOJI $COMMIT_MESSAGE by @$AUTHOR in $URL'

template: |
  ## 🚀 Release Notes - $NEXT_PATCH_VERSION

  $CHANGES

  ### 🗓️ Released on
  $DATE

  ### 🧑‍💻 Contributors
  $CONTRIBUTORS

emoji:
  feat: '✨'
  fix: '🐛'
  docs: '📚'
  refactor: '🔨'
  test: '✅'
  chore: '🧹'
  misc: '📦'
