name: PR CI Test Report

on:
  pull_request:

jobs:
  test-report:
    name: Build and Publish PR Test Report
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Build and run tests
      run: mvn test
      
    - name: Generate HTML report
      run: mvn surefire-report:report-only

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        pip install -r .github/scripts/requirements.txt
        
    - name: Create self-contained report
      run: |
        python .github/scripts/inline_report.py \
          target/reports/surefire.html \
          self-contained-report.html
        
    - name: Upload report
      uses: actions/upload-artifact@v3
      with:
        name: unit-test-report
        path: self-contained-report.html
        retention-days: 7
